name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: build
        run:  yarn build

      - name: copy dist to digital ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PWD }}
          source: ".,!node_modules"
          target: "~/app/gobarber-backend"

      - name: run scripts digital ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PWD }}
          script: |
             cd ~/app/gobarber-backend
             yarn
             ./node_modules/.bin/typeorm migration:run
             pm2 restart flexconsulta-api
